---
title: "ParentMediaPractice"
author: "Karen Li & Shirley Sui"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
---
# Load libraries and files
```{r load libraries and files}
knitr::opts_chunk$set(echo = TRUE)

# libraries
library(tidyverse)
library(readr)
library(survey)
library(gtsummary)
library(magrittr)
library(haven)
library(DescTools)
library(na.tools)

# load data
merged_all <- read_csv('merged_data.csv') # cleaned data including all variables for analysis
full_data <- read_csv('full_demo_data.csv') # used to approximate full dataset, for creation of inclusion exclusion table
orig_COVID_data <- read_dta('COVID_y3.dta') %>% rename(src_subject_id = subjectkey) # used for inclusion exclusion table
```

# Define functions
``` {r define or_ci - p_value - p_val_interaction functions}
# functions to output odds ratio and p vals for a model "m"
or <- function(m) exp(cbind("Odds ratio" = coef(m), confint.default(m, level=0.95)))[1,1]
ci_l <- function(m) exp(cbind("Odds ratio" = coef(m), confint.default(m, level=0.95)))[1,2]
ci_h <- function(m) exp(cbind("Odds ratio" = coef(m), confint.default(m, level=0.95)))[1,3]
p_val <- function(m) (pnorm(abs(coef(summary(m))[, "t value"]), lower.tail=FALSE)*2)[1]
p_val_int <- function(m) (pnorm(abs(coef(summary(m))[, "t value"]), lower.tail=FALSE)*2)[34] # interaction term is 34th term

or_ci <- function(m) {
  odds = round(or(m),2)
  cilow = round(ci_l(m),2)
  cihi = round(ci_h(m),2)
  paste0(odds," (",cilow,", ",cihi,")")
}

p_value <- function(m) {
  p_val = round(p_val(m),4)
  paste0(ifelse(p_val < 0.001, "<0.001", p_val))
}

p_value_int <- function(m) {
  p_val_int = round(p_val_int(m),4)
  paste0(ifelse(p_val_int < 0.001, "<0.001", p_val_int))
}
```

# Prepare data
``` {r data preparation}
# generate subcategory scores for parent media practice
# note that psq_q2_p was reverse coded q2 & with 777 recoded to NA
subcat_scores <- merged_all %>%
  mutate(
    screen_modeling = (psq_q1_p + psq_q2_p)/2, 
    mealtime_screenuse = (psq_q3_p + psq_q4_p)/2,
    bedroom_screenuse = (psq_q5_p + psq_q6_p + psq_q7_p)/3,
    screen_control = (psq_q8_p + psq_q9_p)/2,
    monitor_screentime = (psq_q10_p + psq_q11_p)/2,
    limit_screentime = (psq_q12_p + psq_q13_p + psq_q14_p)/3
  )

# prepare final dataframe and svy.dat
## remove data without propensity scores
## this df is to save the final dataset without applying factor levels and labels
## will later be used to generate inclusion exclusion table
final_norecat <- subset(subcat_scores, !is.na(subcat_scores$acs_raked_propensity_score ))

##remove data without propensity scores
## apply categories (factor levels and labels)
## female: 1=female, 0=male
## race: 1=White, 2=Latino, 3=Black, 4=Asian, 5=Native American, 6=Other
## Parenteduc_new: 1 - HS or less; 0 - > HS
## HHincomebiv_new: 1 - income less than 75000; 0 - >= 75000
## married: 1 - Married or living with partner; 0 - Unmarried or unpartnered
final <- subset(subcat_scores, !is.na(subcat_scores$acs_raked_propensity_score ) ) %>% 
  mutate(
    female = factor(female, levels=c(0,1), labels = c("Male", "Female")), 
    race = factor(race, levels=c(1:6), labels = c("White", "Latino", "Black", "Asian", "Native American", "Other")),
    HHincomebiv_new = factor(HHincomebiv_new, levels=c(0,1), labels = c("Equal to or greater than $75,000", "Less than $75,000")),
    parenteduc_new = factor(parenteduc_new, levels=c(0,1), labels = c("More than high school", "High school or less")),
    married = factor(married, levels=c(1,0), labels = c("Married or living with partner", "Unmarried or unpartnered")),
    COVID_y3 = factor(COVID_y3, levels=c(0,1), labels = c("Before COVID", "During or after COVID"))
  ) #### individuals without propensity score was excluded 


head(final)

data_summary <- summary(final, na.rm = TRUE)
data_summary

write.csv(final, "parentmedia_maturecontent.csv")

svy.dat <- svydesign(ids=~1, data=final,weights=final$acs_raked_propensity_score)
```

# Main Analyses
## Table 1
``` {r Table 1}
desc_table <- svy.dat %>% 
    tbl_svysummary(
    include = c(
      age_w3, 
      female, 
      race, 
      HHincomebiv_new, 
      parenteduc_new, 
      married,
      screen_modeling, 
      mealtime_screenuse, 
      bedroom_screenuse, 
      screen_control, 
      monitor_screentime, 
      limit_screentime, 
      COVID_y3
    ),
    type = list(
      age_w3 ~ "continuous", 
      female ~ "categorical", 
      race ~ "categorical", 
      HHincomebiv_new ~ "categorical", 
      parenteduc_new ~ "categorical",
      married ~ "categorical",
      screen_modeling ~ "continuous", 
      mealtime_screenuse ~ "continuous", 
      bedroom_screenuse ~ "continuous", 
      screen_control ~ "continuous", 
      monitor_screentime ~ "continuous", 
      limit_screentime ~ "continuous", 
      COVID_y3 ~ "categorical"
    ),
    label = list(
      age_w3 ~ "Age (years)", 
      female ~ "Sex (%)", 
      race ~ "Race/ethnicity (%)", 
      HHincomebiv_new ~ "Household income (%)", 
      parenteduc_new ~ "Parents’ highest education (%)", 
      married ~ "Parents' marital status (%)",
      screen_modeling ~ "Parental screen time modeling (mean score)", 
      mealtime_screenuse ~ "Mealtime screen use (mean score)", 
      bedroom_screenuse ~ "Bedroom screen use (mean score)", 
      screen_control ~ "Use of screens to control behavior (mean score)", 
      monitor_screentime ~ "Parental monitoring of screen use (mean score)", 
      limit_screentime ~ "Limiting screen use (mean score)", 
      COVID_y3 ~ "COVID pandemic"
    ),    
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{p}%"
    ),
    digits = list(
      all_continuous() ~ c(2, 2),
      all_categorical() ~ 1
    ),
    missing = "no"
  ) 

# add category for Parent media practices
library(tibble)
tab <- desc_table[["table_body"]] %>% 
  add_row(
    variable = "Media parenting practices", 
    var_type = "categorical", 
    var_label = "Media parenting practices", 
    row_type = "label", 
    label = "Media parenting practices", 
    stat_0 = NA, 
    .before = 21)

desc_table[["table_body"]] <- tab

# and convert each subcategory to level
desc_table[["table_body"]][["row_type"]][c(22:27)] <- "level"

table_1 <- desc_table %>%
  modify_header(
    label = "**Sociodemographic characteristics**", 
    stat_0 = "**Mean (SD) / %**"
  ) %>%
  bold_labels() %>%
  modify_footnote(update = everything() ~ NA) %>% 
  modify_caption("<div style='text-align: left; color: grey'><b>Table 1.</b> Sociodemographic and youth screen time characteristics of Adolescent Brain Cognitive Development (ABCD) Study participants at Year 3 (<em>N</em> = 10,054).</div>")

table_1
```

## Table 2
```{r Table 2}
# screen13_y = How often do you play mature-rated video games (e.g., Call of Duty, Grand Theft Auto, Assassin's Creed, etc.)?
# screen14_y = How often do you watch R-rated movies?

# outcome = mature video game, exposure = screen modeling
svyolr_vidgame_screenmodel_married = svyolr(factor(screen13_y) ~ screen_modeling + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = R rated movies, exposure = screen modeling
svyolr_rmovie_screenmodel_married = svyolr(factor(screen14_y) ~ screen_modeling + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = mature video game, exposure = mealtime screenuse
svyolr_vidgame_mealtimeuse_married = svyolr(factor(screen13_y) ~ mealtime_screenuse + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = R rated movies, exposure = mealtime screenuse
svyolr_rmovie_mealtimeuse_married = svyolr(factor(screen14_y) ~ mealtime_screenuse + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = mature video game, exposure = bedroom screenuse
svyolr_vidgame_bedroomuse_married = svyolr(factor(screen13_y) ~ bedroom_screenuse + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = R rated movies, exposure = bedroom screenuse
svyolr_rmovie_bedroomuse_married = svyolr(factor(screen14_y) ~ bedroom_screenuse + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = mature video game, exposure = screen control
svyolr_vidgame_screencontrol_married = svyolr(factor(screen13_y) ~ screen_control + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = mature video game, exposure = reward for positive behavior
svyolr_vidgame_reward_married = svyolr(factor(screen13_y) ~ psq_q8_p + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = mature video game, exposure = punishment for bad behavior
svyolr_vidgame_punish_married = svyolr(factor(screen13_y) ~ psq_q9_p + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = R rated movies, exposure = screen control
svyolr_rmovie_screencontrol_married = svyolr(factor(screen14_y) ~ screen_control + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat) 

# outcome = R rated movie, exposure = reward for positive behavior
svyolr_rmovie_reward_married = svyolr(factor(screen14_y) ~ psq_q8_p + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = R rated movie, exposure = punishment for bad behavior
svyolr_rmovie_punish_married = svyolr(factor(screen14_y) ~ psq_q9_p + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = mature video game, exposure = monitor screentime
svyolr_vidgame_monitor_married = svyolr(factor(screen13_y) ~ monitor_screentime + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = R rated movies, exposure = monitor screentime
svyolr_rmovie_monitor_married = svyolr(factor(screen14_y) ~ monitor_screentime + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = mature video game, exposure = limit screentime
svyolr_vidgame_limit_married = svyolr(factor(screen13_y) ~ limit_screentime + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# outcome = R rated movies, exposure = limit screentime
svyolr_rmovie_limit_married = svyolr(factor(screen14_y) ~ limit_screentime + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(married) + factor(site_id) + factor(COVID_y3), design=svy.dat)

# table 2 summary
categories <- c(
    "",
    "Parental screen time modeling",
    "Mealtime screen use",
    "Bedroom screen use",
    "Use of screens to control behavior",
    "Parental monitoring of screen time",
    "Limiting screen time"
)
vidgames <- c("Odds Ratio (95% CI)",
  or_ci(svyolr_vidgame_screenmodel_married), 
  or_ci(svyolr_vidgame_mealtimeuse_married), 
  or_ci(svyolr_vidgame_bedroomuse_married), 
  or_ci(svyolr_vidgame_screencontrol_married), 
  or_ci(svyolr_vidgame_monitor_married), 
  or_ci(svyolr_vidgame_limit_married)
)
# vidgames_p <- c("",
#   p_value(svyolr_vidgame_screenmodel_married), 
#   p_value(svyolr_vidgame_mealtimeuse_married), 
#   p_value(svyolr_vidgame_bedroomuse_married), 
#   p_value(svyolr_vidgame_screencontrol_married), 
#   p_value(svyolr_vidgame_monitor_married), 
#   p_value(svyolr_vidgame_limit_married)
# )
rmovie <- c(
  "Odds Ratio (95% CI)", 
  or_ci(svyolr_rmovie_screenmodel_married),
  or_ci(svyolr_rmovie_mealtimeuse_married),
  or_ci(svyolr_rmovie_bedroomuse_married),
  or_ci(svyolr_rmovie_screencontrol_married),
  or_ci(svyolr_rmovie_monitor_married),
  or_ci(svyolr_rmovie_limit_married)
)
# rmovie_p <- c("",
#   p_value(svyolr_rmovie_screenmodel_married),
#   p_value(svyolr_rmovie_mealtimeuse_married),
#   p_value(svyolr_rmovie_bedroomuse_married),
#   p_value(svyolr_rmovie_screencontrol_married),
#   p_value(svyolr_rmovie_monitor_married),
#   p_value(svyolr_rmovie_limit_married)
# )
table2 <- tibble(
  "Media parenting practice categories" = categories,
  "Frequency of Mature Video Games" = vidgames,
#  "Mature Video Games p-value" = vidgames_p,
  "R-rated Movies Consumption" = rmovie
#  "R-rated Movies p-value" = rmovie_p
)

table2
```

# Appendices
## Appendix A
``` {r Appendix A: inclusion exclusion table}
# anti-join final data to full data
# final data uses final_norecat (n=10054)
# full data uses full_data (n=11875)

# correct data type for some columns + add eligibility column
excluded <- anti_join(full_data,final_norecat) %>% merge(orig_COVID_data, by = c("src_subject_id")) %>%
  mutate(
    female = factor(female, levels=c(0,1), labels = c("Male", "Female")),
    race = factor(race, levels=c(1:6), labels = c("White", "Latino", "Black", "Asian", "Native American", "Other")),
    HHincomebiv_new = factor(HHincomebiv_new, levels=c(0,1), labels = c("Equal to or greater than $75,000", "Less than $75,000")),
    parenteduc_new = factor(parenteduc_new, levels=c(0,1), labels = c("More than high school", "High school or less")),
    married = factor(married, levels=c(1,0), labels = c("Married or living with partner", "Unmarried or unpartnered")),
    COVID_y3 = factor(COVID_y3, levels=c(0,1), labels = c("Before COVID", "During or after COVID")),
  ) %>%
  mutate(eligibility = "excluded")

included <- final %>%
  mutate(eligibility = "included")

# combine excluded and included
ie <- full_join(included,excluded)
ie_weights <- ie %>% filter(!is.na(acs_raked_propensity_score))
ie.svy.dat <- svydesign(ids=~1, data=ie_weights,weights=ie_weights$acs_raked_propensity_score)

ie_table <- ie.svy.dat %>% 
    tbl_svysummary(
    by = eligibility,
    include = c(
      age_w3, 
      female, 
      race, 
      HHincomebiv_new, 
      parenteduc_new, 
      married,
      COVID_y3
    ),
    type = list(
      age_w3 ~ "continuous", 
      female ~ "categorical", 
      race ~ "categorical", 
      HHincomebiv_new ~ "categorical", 
      parenteduc_new ~ "categorical",  
      married ~ "categorical",
      COVID_y3 ~ "categorical"
    ),
    label = list(
      age_w3 ~ "Age (years)", 
      female ~ "Sex (%)", 
      race ~ "Race/ethnicity (%)", 
      HHincomebiv_new ~ "Household income (%)", 
      parenteduc_new ~ "Parents’ highest education (%)",  
      married ~ "Parents' marital status (%)",
      COVID_y3 ~ "COVID pandemic"
    ),    
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_categorical() ~ "{p}%"
    ),
    digits = list(
      all_continuous() ~ c(2, 2),
      all_categorical() ~ 1
    ),
    missing = "no"
  ) 

ie_table <- ie_table %>%
  modify_header(
    label = "**Sociodemographic characteristics**",
    stat_1 = "Excluded",
    stat_2 = "Included"
  ) %>%
  bold_labels() %>%
  # modify_footnote(update = everything() ~ NA) %>%
  modify_caption("<div style='text-align: left; color: grey'><b>Appendix A.</b> Comparison of sociodemographic characteristics between included and excluded Adolescent Brain Cognitive Development (ABCD) study participants.</div>") %>%
  add_p()

# print table
ie_table
```

## Appendix C
``` {r Appendix C: correlation table}
library(corrplot)

# Correlation matrix between parent media practices 
corr_data_pmp = data.frame(final$screen_modeling
                          , final$mealtime_screenuse
                          , final$bedroom_screenuse
                          , final$screen_control
                          , final$monitor_screentime
                          , final$limit_screentime)
colnames(corr_data_pmp) <- c("1. Parental screen time modeling"
                             , "2. Mealtime screen use"
                             , "3. Bedroom screen use"
                             , "4. Use of screens to control behavior"
                             , "5. Parental monitoring of screen time"
                             , "6. Limiting screen time")
M = cor(na.omit(corr_data_pmp))
M_plot = corrplot(M
                  , method = 'number'
                  , tl.col = 'black'
                  , order = 'alphabet'
                  , title = 'Appendix C. Correlation table between parent media practices in the \nAdolescent Brain Cognitive Development (ABCD) study (N = 10,054).'
                  , tl.srt = 45
                  , col = COL2('RdBu', 10)
                  , mar=c(0, 0, 1, 1)
                  , col.lim = c(-1,1))
M
```

## Appendix D
``` {r Appendix D: reward or punishment with marital as covar}
# reward vs punish - svyolr
categories <- c(
    "",
    "I offer screen time to my child as a reward for good behavior.",
    "I take away screen time from my child as a punishment for bad behavior."
)
vidgames <- c("Odds Ratio (95% CI)",
  or_ci(svyolr_vidgame_reward_married), 
  or_ci(svyolr_vidgame_punish_married)
)
rmovie <- c(
  "Odds Ratio (95% CI)", 
  or_ci(svyolr_rmovie_reward_married),
  or_ci(svyolr_rmovie_punish_married)
)
appD_marital <- tibble(
  "Media parenting practice question" = categories,
  "Frequency of Mature Video Games" = vidgames,
  "R-rated Movies Consumption" = rmovie
)

appD_marital
```

## Appendix E
### Stratified models
``` {r Appendix E: sex at birth STRATIFIED - models}
# screen13_y = How often do you play mature-rated video games (e.g., Call of Duty, Grand Theft Auto, Assassin's Creed, etc.)?
# screen14_y = How often do you watch R-rated movies?

# Subset parent education datasets
female <- final %>% subset(female == "Female") # 4772 observations
male <- final %>% subset(female == "Male") # 5280 observations

final_no_sex <- final %>% filter(!is.na(female))

# Apply propensity weights
svy.sex <- svydesign(ids=~1, data = final_no_sex, weights = final_no_sex$acs_raked_propefinalnsity_score, strata = ~final_no_sex$female)
svy.dat.female <- svydesign(ids=~1, data=female, weights=female$acs_raked_propensity_score)
svy.dat.male <- svydesign(ids=~1, data=male, weights=male$acs_raked_propensity_score)

# outcome = mature video game, exposure = screen modeling, less than $75k
svyolr_vidgame_screenmodel_female = svyolr(factor(screen13_y) ~ screen_modeling + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat.female)
# outcome = mature video game, exposure = screen modeling, more than $75k
svyolr_vidgame_screenmodel_male = svyolr(factor(screen13_y) ~ screen_modeling + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat.male)

# outcome = R rated movie, exposure = screen modeling, less than $75k
svyolr_rmovie_screenmodel_female = svyolr(factor(screen14_y) ~ screen_modeling + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat.female)
# outcome = R rated movie, exposure = screen modeling, more than $75k
svyolr_rmovie_screenmodel_male = svyolr(factor(screen14_y) ~ screen_modeling + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat.male)

# outcome = mature video game, exposure = mealtime screenuse, less than $75k
svyolr_vidgame_mealtimeuse_female = svyolr(factor(screen13_y) ~ mealtime_screenuse + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.female)
# outcome = mature video game, exposure = mealtime screenuse, more than $75k
svyolr_vidgame_mealtimeuse_male = svyolr(factor(screen13_y) ~ mealtime_screenuse + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.male)

# outcome = R rated movie, exposure = mealtime screenuse, less than $75k
svyolr_rmovie_mealtimeuse_female = svyolr(factor(screen14_y) ~ mealtime_screenuse + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.female)
# outcome = R rated movie, exposure = mealtime screenuse, more than $75k
svyolr_rmovie_mealtimeuse_male = svyolr(factor(screen14_y) ~ mealtime_screenuse + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.male)

# outcome = mature video game, exposure = bedroom screenuse, less than $75k
svyolr_vidgame_bedroomuse_female = svyolr(factor(screen13_y) ~ bedroom_screenuse + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.female)
# outcome = mature video game, exposure = bedroom screenuse, more than $75k
svyolr_vidgame_bedroomuse_male = svyolr(factor(screen13_y) ~ bedroom_screenuse + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.male)

# outcome = R rated movie, exposure = bedroom screenuse, less than $75k
svyolr_rmovie_bedroomuse_female = svyolr(factor(screen14_y) ~ bedroom_screenuse + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.female)
# outcome = R rated movie, exposure = bedroom screenuse, more than $75k
svyolr_rmovie_bedroomuse_male = svyolr(factor(screen14_y) ~ bedroom_screenuse + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.male)

# outcome = mature video game, exposure = screen control, less than $75k
svyolr_vidgame_screencontrol_female = svyolr(factor(screen13_y) ~ screen_control + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.female)
# outcome = mature video game, exposure = screen control, more than $75k
svyolr_vidgame_screencontrol_male = svyolr(factor(screen13_y) ~ screen_control + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.male)

# outcome = R rated movie, exposure = screen control, less than $75k
svyolr_rmovie_screencontrol_female = svyolr(factor(screen14_y) ~ screen_control + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.female)
# outcome = R rated movie, exposure = screen control, more than $75k
svyolr_rmovie_screencontrol_male = svyolr(factor(screen14_y) ~ screen_control + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.male)

# outcome = mature video game, exposure = monitor screentime, less than $75k
svyolr_vidgame_monitor_female = svyolr(factor(screen13_y) ~ monitor_screentime + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.female)
# outcome = mature video game, exposure = monitor screentime, more than $75k
svyolr_vidgame_monitor_male = svyolr(factor(screen13_y) ~ monitor_screentime + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.male)

# outcome = R rated movie, exposure = monitor screentime, less than $75k
svyolr_rmovie_monitor_female = svyolr(factor(screen14_y) ~ monitor_screentime + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.female)
# outcome = R rated movie, exposure = monitor screentime, more than $75k
svyolr_rmovie_monitor_male = svyolr(factor(screen14_y) ~ monitor_screentime + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.male)

# outcome = mature video game, exposure = limit screentime, less than $75k
svyolr_vidgame_limit_female = svyolr(factor(screen13_y) ~ limit_screentime + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.female)
# outcome = mature video game, exposure = limit screentime, more than $75k
svyolr_vidgame_limit_male = svyolr(factor(screen13_y) ~ limit_screentime + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.male)

# outcome = R rated movie, exposure = limit screentime, less than $75k
svyolr_rmovie_limit_female = svyolr(factor(screen14_y) ~ limit_screentime + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.female)
# outcome = R rated movie, exposure = limit screentime, more than $75k
svyolr_rmovie_limit_male = svyolr(factor(screen14_y) ~ limit_screentime + age_w3 + factor(HHincomebiv_new) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.male)
```

### Interaction models
```{r Appendix E: sex at birth INTERACTION - models}
# outcome = mature video game, exposure = screen modeling
svyolr_vidgame_screenmodel_sex = svyolr(factor(screen13_y) ~ screen_modeling*factor(female) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = screen modeling
svyolr_rmovie_screenmodel_sex = svyolr(factor(screen14_y) ~ screen_modeling*factor(female) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = mature video game, exposure = mealtime screenuse
svyolr_vidgame_mealtimeuse_sex  = svyolr(factor(screen13_y) ~ mealtime_screenuse*factor(female) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat)

# outcome = R rated movies, exposure = mealtime screenuse
svyolr_rmovie_mealtimeuse_sex  = svyolr(factor(screen14_y) ~ mealtime_screenuse*factor(female) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = mature video game, exposure = bedroom screenuse
svyolr_vidgame_bedroomuse_sex = svyolr(factor(screen13_y) ~ bedroom_screenuse*factor(female) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = bedroom screenuse
svyolr_rmovie_bedroomuse_sex = svyolr(factor(screen14_y) ~ bedroom_screenuse*factor(female) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = mature video game, exposure = screen control
svyolr_vidgame_screencontrol_sex = svyolr(factor(screen13_y) ~ screen_control*factor(female) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = screen control
svyolr_rmovie_screencontrol_sex = svyolr(factor(screen14_y) ~ screen_control*factor(female) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat) 

# outcome = mature video game, exposure = monitor screentime
svyolr_vidgame_monitor_sex = svyolr(factor(screen13_y) ~ monitor_screentime*factor(female) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = monitor screentime
svyolr_rmovie_monitor_sex = svyolr(factor(screen14_y) ~ monitor_screentime*factor(female) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = mature video game, exposure = limit screentime
svyolr_vidgame_limit_sex = svyolr(factor(screen13_y) ~ limit_screentime*factor(female) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = limit screentime
svyolr_rmovie_limit_sex = svyolr(factor(screen14_y) ~ limit_screentime*factor(female) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)
```

### Tables
``` {r Appendix E: tables}
categories <- c(
    "",
    "Parental screen time modeling",
    "Mealtime screen use",
    "Bedroom screen use",
    "Use of screens to control behavior",
    "Parental monitoring of screen time",
    "Limiting screen time"
)
vidgames_female <- c("Odds Ratio (95% CI)",
  or_ci(svyolr_vidgame_screenmodel_female), 
  or_ci(svyolr_vidgame_mealtimeuse_female), 
  or_ci(svyolr_vidgame_bedroomuse_female), 
  or_ci(svyolr_vidgame_screencontrol_female), 
  or_ci(svyolr_vidgame_monitor_female), 
  or_ci(svyolr_vidgame_limit_female)
)
vidgames_female_p <- c("",
  p_value(svyolr_vidgame_screenmodel_female), 
  p_value(svyolr_vidgame_mealtimeuse_female), 
  p_value(svyolr_vidgame_bedroomuse_female), 
  p_value(svyolr_vidgame_screencontrol_female), 
  p_value(svyolr_vidgame_monitor_female), 
  p_value(svyolr_vidgame_limit_female)                     
)
rmovie_female <- c(
  "Odds Ratio (95% CI)", 
  or_ci(svyolr_rmovie_screenmodel_female),
  or_ci(svyolr_rmovie_mealtimeuse_female),
  or_ci(svyolr_rmovie_bedroomuse_female),
  or_ci(svyolr_rmovie_screencontrol_female),
  or_ci(svyolr_rmovie_monitor_female),
  or_ci(svyolr_rmovie_limit_female)
)
rmovie_female_p <- c(
  "",
  p_value(svyolr_rmovie_screenmodel_female),
  p_value(svyolr_rmovie_mealtimeuse_female),
  p_value(svyolr_rmovie_bedroomuse_female),
  p_value(svyolr_rmovie_screencontrol_female),
  p_value(svyolr_rmovie_monitor_female),
  p_value(svyolr_rmovie_limit_female)
)
vidgames_male <- c("Odds Ratio (95% CI)",
  or_ci(svyolr_vidgame_screenmodel_male), 
  or_ci(svyolr_vidgame_mealtimeuse_male), 
  or_ci(svyolr_vidgame_bedroomuse_male), 
  or_ci(svyolr_vidgame_screencontrol_male), 
  or_ci(svyolr_vidgame_monitor_male), 
  or_ci(svyolr_vidgame_limit_male)
)
vidgames_male_p <- c(
  "",
  p_value(svyolr_vidgame_screenmodel_male), 
  p_value(svyolr_vidgame_mealtimeuse_male), 
  p_value(svyolr_vidgame_bedroomuse_male), 
  p_value(svyolr_vidgame_screencontrol_male), 
  p_value(svyolr_vidgame_monitor_male), 
  p_value(svyolr_vidgame_limit_male)
)
rmovie_male <- c(
  "Odds Ratio (95% CI)", 
  or_ci(svyolr_rmovie_screenmodel_male),
  or_ci(svyolr_rmovie_mealtimeuse_male),
  or_ci(svyolr_rmovie_bedroomuse_male),
  or_ci(svyolr_rmovie_screencontrol_male),
  or_ci(svyolr_rmovie_monitor_male),
  or_ci(svyolr_rmovie_limit_male)
)
rmovie_male_p <- c(
  "",
  p_value(svyolr_rmovie_screenmodel_male),
  p_value(svyolr_rmovie_mealtimeuse_male),
  p_value(svyolr_rmovie_bedroomuse_male),
  p_value(svyolr_rmovie_screencontrol_male),
  p_value(svyolr_rmovie_monitor_male),
  p_value(svyolr_rmovie_limit_male)
)
appE_stratbysex <- tibble(
  "Media parenting practice categories" = categories,
  "Frequency of Mature Video Games (Female)" = vidgames_female,
  "Mature Video Games (Female) p-value" = vidgames_female_p,
  "R-rated Movies Consumption (Female)" = rmovie_female,
  "R-rated Movies (Female) p-value" = rmovie_female_p,
  "Frequency of Mature Video Games (Male)" = vidgames_male,
  "Mature Video Games (Male) p-value" = vidgames_male_p,
  "R-rated Movies Consumption (Male)" = rmovie_male,
  "R-rated Movies (Male)" = rmovie_male_p
)

appE_stratbysex

# Make interaction term p-value table
vidgames_sex_p <- c(
  "",
  p_value_int(svyolr_vidgame_screenmodel_sex), 
  p_value_int(svyolr_vidgame_mealtimeuse_sex), 
  p_value_int(svyolr_vidgame_bedroomuse_sex), 
  p_value_int(svyolr_vidgame_screencontrol_sex), 
  p_value_int(svyolr_vidgame_monitor_sex), 
  p_value_int(svyolr_vidgame_limit_sex)
)
rmovie_sex_p <- c(
  "",
  p_value_int(svyolr_rmovie_screenmodel_sex), 
  p_value_int(svyolr_rmovie_mealtimeuse_sex), 
  p_value_int(svyolr_rmovie_bedroomuse_sex), 
  p_value_int(svyolr_rmovie_screencontrol_sex), 
  p_value_int(svyolr_rmovie_monitor_sex), 
  p_value_int(svyolr_rmovie_limit_sex)
)
appE_sexint <- tibble(
  "Media parenting practice categories" = categories,
  "Frequency of Mature Video Games" = vidgames_sex_p,
  "R-rated Movies Consumption" = rmovie_sex_p
)

appE_sexint
```

## Appendix F
### Stratified models
```{r Appendix F: binary parent education STRATIFIED - models}
# screen13_y = How often do you play mature-rated video games (e.g., Call of Duty, Grand Theft Auto, Assassin's Creed, etc.)?
# screen14_y = How often do you watch R-rated movies?

# Subset parent education datasets
hs_or_less <- final %>% subset(parenteduc_new == "High school or less")
more_than_hs <- final %>% subset(parenteduc_new == "More than high school")

# Apply propensity weights
svy.dat.hs.less <- svydesign(ids=~1, data=hs_or_less,weights=hs_or_less$acs_raked_propensity_score)
svy.dat.hs.more <- svydesign(ids=~1, data=more_than_hs,weights=more_than_hs$acs_raked_propensity_score)

# outcome = mature video game, exposure = screen modeling, HS or less
svyolr_vidgame_screenmodel_hs_less = svyolr(factor(screen13_y) ~ screen_modeling + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat.hs.less)
# outcome = mature video game, exposure = screen modeling, more than HS
svyolr_vidgame_screenmodel_hs_more = svyolr(factor(screen13_y) ~ screen_modeling + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat.hs.more)

# outcome = R rated movie, exposure = screen modeling, HS or less
svyolr_rmovie_screenmodel_hs_less = svyolr(factor(screen14_y) ~ screen_modeling + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat.hs.less)
# outcome = R rated movie, exposure = screen modeling, more than HS
svyolr_rmovie_screenmodel_hs_more = svyolr(factor(screen14_y) ~ screen_modeling + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat.hs.more)

# outcome = mature video game, exposure = mealtime screenuse, less than HS
svyolr_vidgame_mealtimeuse_hs_less = svyolr(factor(screen13_y) ~ mealtime_screenuse + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.less)
# outcome = mature video game, exposure = mealtime screenuse, more than HS
svyolr_vidgame_mealtimeuse_hs_more = svyolr(factor(screen13_y) ~ mealtime_screenuse + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.more)

# outcome = R rated movie, exposure = mealtime screenuse, less than HS
svyolr_rmovie_mealtimeuse_hs_less = svyolr(factor(screen14_y) ~ mealtime_screenuse + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.less)
# outcome = R rated movie, exposure = mealtime screenuse, more than HS
svyolr_rmovie_mealtimeuse_hs_more = svyolr(factor(screen14_y) ~ mealtime_screenuse + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.more)

# outcome = mature video game, exposure = bedroom screenuse, less than HS
svyolr_vidgame_bedroomuse_hs_less = svyolr(factor(screen13_y) ~ bedroom_screenuse + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.less)
# outcome = mature video game, exposure = bedroom screenuse, more than HS
svyolr_vidgame_bedroomuse_hs_more = svyolr(factor(screen13_y) ~ bedroom_screenuse + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.more)

# outcome = R rated movie, exposure = bedroom screenuse, less than HS
svyolr_rmovie_bedroomuse_hs_less = svyolr(factor(screen14_y) ~ bedroom_screenuse + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.less)
# outcome = R rated movie, exposure = bedroom screenuse, more than HS
svyolr_rmovie_bedroomuse_hs_more = svyolr(factor(screen14_y) ~ bedroom_screenuse + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.more)

# outcome = mature video game, exposure = screen control, less than HS
svyolr_vidgame_screencontrol_hs_less = svyolr(factor(screen13_y) ~ screen_control + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.less)
# outcome = mature video game, exposure = screen control, more than HS
svyolr_vidgame_screencontrol_hs_more = svyolr(factor(screen13_y) ~ screen_control + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.more)

# outcome = R rated movie, exposure = screen control, less than HS
svyolr_rmovie_screencontrol_hs_less = svyolr(factor(screen14_y) ~ screen_control + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.less)
# outcome = R rated movie, exposure = screen control, more than HS
svyolr_rmovie_screencontrol_hs_more = svyolr(factor(screen14_y) ~ screen_control + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.more)

# outcome = mature video game, exposure = monitor screentime, less than HS
svyolr_vidgame_monitor_hs_less = svyolr(factor(screen13_y) ~ monitor_screentime + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.less)
# outcome = mature video game, exposure = monitor screentime, more than HS
svyolr_vidgame_monitor_hs_more = svyolr(factor(screen13_y) ~ monitor_screentime + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.more)

# outcome = R rated movie, exposure = monitor screentime, less than HS
svyolr_rmovie_monitor_hs_less = svyolr(factor(screen14_y) ~ monitor_screentime + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.less)
# outcome = R rated movie, exposure = monitor screentime, more than HS
svyolr_rmovie_monitor_hs_more = svyolr(factor(screen14_y) ~ monitor_screentime + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.more)

# outcome = mature video game, exposure = limit screentime, less than HS
svyolr_vidgame_limit_hs_less = svyolr(factor(screen13_y) ~ limit_screentime + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.less)
# outcome = mature video game, exposure = limit screentime, more than HS
svyolr_vidgame_limit_hs_more = svyolr(factor(screen13_y) ~ limit_screentime + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.more)

# outcome = R rated movie, exposure = limit screentime, less than HS
svyolr_rmovie_limit_hs_less = svyolr(factor(screen14_y) ~ limit_screentime + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.less)
# outcome = R rated movie, exposure = limit screentime, more than HS
svyolr_rmovie_limit_hs_more = svyolr(factor(screen14_y) ~ limit_screentime + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.hs.more)
```

### Interaction models
```{r Appendix F: binary parent education INTERACTION - models}
# outcome = mature video game, exposure = screen modeling
svyolr_vidgame_screenmodel_educ = svyolr(factor(screen13_y) ~ screen_modeling*factor(parenteduc_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = screen modeling
svyolr_rmovie_screenmodel_educ = svyolr(factor(screen14_y) ~ screen_modeling*factor(parenteduc_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = mature video game, exposure = mealtime screenuse
svyolr_vidgame_mealtimeuse_educ  = svyolr(factor(screen13_y) ~ mealtime_screenuse*factor(parenteduc_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat)

# outcome = R rated movies, exposure = mealtime screenuse
svyolr_rmovie_mealtimeuse_educ  = svyolr(factor(screen14_y) ~ mealtime_screenuse*factor(parenteduc_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = mature video game, exposure = bedroom screenuse
svyolr_vidgame_bedroomuse_educ = svyolr(factor(screen13_y) ~ bedroom_screenuse*factor(parenteduc_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = bedroom screenuse
svyolr_rmovie_bedroomuse_educ = svyolr(factor(screen14_y) ~ bedroom_screenuse*factor(parenteduc_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = mature video game, exposure = screen control
svyolr_vidgame_screencontrol_educ = svyolr(factor(screen13_y) ~ screen_control*factor(parenteduc_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = screen control
svyolr_rmovie_screencontrol_educ = svyolr(factor(screen14_y) ~ screen_control*factor(parenteduc_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat) 

# outcome = mature video game, exposure = monitor screentime
svyolr_vidgame_monitor_educ = svyolr(factor(screen13_y) ~ monitor_screentime*factor(parenteduc_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = monitor screentime
svyolr_rmovie_monitor_educ = svyolr(factor(screen14_y) ~ monitor_screentime*factor(parenteduc_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = mature video game, exposure = limit screentime
svyolr_vidgame_limit_educ = svyolr(factor(screen13_y) ~ limit_screentime*factor(parenteduc_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = limit screentime
svyolr_rmovie_limit_educ = svyolr(factor(screen14_y) ~ limit_screentime*factor(parenteduc_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)
```

### Tables
``` {r Appendix F: tables}
categories <- c(
    "",
    "Parental screen time modeling",
    "Mealtime screen use",
    "Bedroom screen use",
    "Use of screens to control behavior",
    "Parental monitoring of screen time",
    "Limiting screen time"
)
vidgames_hs_less <- c("Odds Ratio (95% CI)",
  or_ci(svyolr_vidgame_screenmodel_hs_less), 
  or_ci(svyolr_vidgame_mealtimeuse_hs_less), 
  or_ci(svyolr_vidgame_bedroomuse_hs_less), 
  or_ci(svyolr_vidgame_screencontrol_hs_less), 
  or_ci(svyolr_vidgame_monitor_hs_less), 
  or_ci(svyolr_vidgame_limit_hs_less)
)
vidgames_hs_less_p <- c("",
  p_value(svyolr_vidgame_screenmodel_hs_less), 
  p_value(svyolr_vidgame_mealtimeuse_hs_less), 
  p_value(svyolr_vidgame_bedroomuse_hs_less), 
  p_value(svyolr_vidgame_screencontrol_hs_less), 
  p_value(svyolr_vidgame_monitor_hs_less), 
  p_value(svyolr_vidgame_limit_hs_less)                     
)
rmovie_hs_less <- c(
  "Odds Ratio (95% CI)", 
  or_ci(svyolr_rmovie_screenmodel_hs_less),
  or_ci(svyolr_rmovie_mealtimeuse_hs_less),
  or_ci(svyolr_rmovie_bedroomuse_hs_less),
  or_ci(svyolr_rmovie_screencontrol_hs_less),
  or_ci(svyolr_rmovie_monitor_hs_less),
  or_ci(svyolr_rmovie_limit_hs_less)
)
rmovie_hs_less_p <- c(
  "",
  p_value(svyolr_rmovie_screenmodel_hs_less),
  p_value(svyolr_rmovie_mealtimeuse_hs_less),
  p_value(svyolr_rmovie_bedroomuse_hs_less),
  p_value(svyolr_rmovie_screencontrol_hs_less),
  p_value(svyolr_rmovie_monitor_hs_less),
  p_value(svyolr_rmovie_limit_hs_less)
)
vidgames_hs_more <- c("Odds Ratio (95% CI)",
  or_ci(svyolr_vidgame_screenmodel_hs_more), 
  or_ci(svyolr_vidgame_mealtimeuse_hs_more), 
  or_ci(svyolr_vidgame_bedroomuse_hs_more), 
  or_ci(svyolr_vidgame_screencontrol_hs_more), 
  or_ci(svyolr_vidgame_monitor_hs_more), 
  or_ci(svyolr_vidgame_limit_hs_more)
)
vidgames_hs_more_p <- c(
  "",
  p_value(svyolr_vidgame_screenmodel_hs_more), 
  p_value(svyolr_vidgame_mealtimeuse_hs_more), 
  p_value(svyolr_vidgame_bedroomuse_hs_more), 
  p_value(svyolr_vidgame_screencontrol_hs_more), 
  p_value(svyolr_vidgame_monitor_hs_more), 
  p_value(svyolr_vidgame_limit_hs_more)
)
rmovie_hs_more <- c(
  "Odds Ratio (95% CI)", 
  or_ci(svyolr_rmovie_screenmodel_hs_more),
  or_ci(svyolr_rmovie_mealtimeuse_hs_more),
  or_ci(svyolr_rmovie_bedroomuse_hs_more),
  or_ci(svyolr_rmovie_screencontrol_hs_more),
  or_ci(svyolr_rmovie_monitor_hs_more),
  or_ci(svyolr_rmovie_limit_hs_more)
)
rmovie_hs_more_p <- c(
  "",
  p_value(svyolr_rmovie_screenmodel_hs_more),
  p_value(svyolr_rmovie_mealtimeuse_hs_more),
  p_value(svyolr_rmovie_bedroomuse_hs_more),
  p_value(svyolr_rmovie_screencontrol_hs_more),
  p_value(svyolr_rmovie_monitor_hs_more),
  p_value(svyolr_rmovie_limit_hs_more)
)
appF_stratbyeduc <- tibble(
  "Media parenting practice categories" = categories,
  "Frequency of Mature Video Games (HS or less)" = vidgames_hs_less,
  "Mature Video Games (HS or less) p-value" = vidgames_hs_less_p,
  "R-rated Movies Consumption (HS or less)" = rmovie_hs_less,
  "R-rated Movies (HS or less) p-value" = rmovie_hs_less_p,
  "Frequency of Mature Video Games (More than HS)" = vidgames_hs_more,
  "Mature Video Games (More than HS) p-value" = vidgames_hs_more_p,
  "R-rated Movies Consumption (More than HS)" = rmovie_hs_more,
  "R-rated Movies (More than HS)" = rmovie_hs_more_p
)

appF_stratbyeduc

# Make interaction term p-value table
vidgames_educ_p <- c(
  "",
  p_value_int(svyolr_vidgame_screenmodel_educ), 
  p_value_int(svyolr_vidgame_mealtimeuse_educ), 
  p_value_int(svyolr_vidgame_bedroomuse_educ), 
  p_value_int(svyolr_vidgame_screencontrol_educ), 
  p_value_int(svyolr_vidgame_monitor_educ), 
  p_value_int(svyolr_vidgame_limit_educ)
)
rmovie_educ_p <- c(
  "",
  p_value_int(svyolr_rmovie_screenmodel_educ), 
  p_value_int(svyolr_rmovie_mealtimeuse_educ), 
  p_value_int(svyolr_rmovie_bedroomuse_educ), 
  p_value_int(svyolr_rmovie_screencontrol_educ), 
  p_value_int(svyolr_rmovie_monitor_educ), 
  p_value_int(svyolr_rmovie_limit_educ)
)
appF_educint <- tibble(
  "Media parenting practice categories" = categories,
  "Frequency of Mature Video Games" = vidgames_educ_p,
  "R-rated Movies Consumption" = rmovie_educ_p
)

appF_educint
```

## Appendix G
### Stratified models
```{r Appendix G: binary household income STRATIFIED - models}
# screen13_y = How often do you play mature-rated video games (e.g., Call of Duty, Grand Theft Auto, Assassin's Creed, etc.)?
# screen14_y = How often do you watch R-rated movies?

# Subset parent education datasets
less_75k <- final %>% subset(HHincomebiv_new == "Less than $75,000") #  2496 observations
more_75k <- final %>% subset(HHincomebiv_new == "Equal to or greater than $75,000") # 6797 observations

# Apply propensity weights
svy.dat.less.75k <- svydesign(ids=~1, data=less_75k,weights=less_75k$acs_raked_propensity_score)
svy.dat.more.75k <- svydesign(ids=~1, data=more_75k,weights=more_75k$acs_raked_propensity_score)

# outcome = mature video game, exposure = screen modeling, less than $75k
svyolr_vidgame_screenmodel_less_75k = svyolr(factor(screen13_y) ~ screen_modeling + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat.less.75k)
# outcome = mature video game, exposure = screen modeling, more than $75k
svyolr_vidgame_screenmodel_more_75k = svyolr(factor(screen13_y) ~ screen_modeling + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat.more.75k)

# outcome = R rated movie, exposure = screen modeling, less than $75k
svyolr_rmovie_screenmodel_less_75k = svyolr(factor(screen14_y) ~ screen_modeling + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat.less.75k)
# outcome = R rated movie, exposure = screen modeling, more than $75k
svyolr_rmovie_screenmodel_more_75k = svyolr(factor(screen14_y) ~ screen_modeling + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat.more.75k)

# outcome = mature video game, exposure = mealtime screenuse, less than $75k
svyolr_vidgame_mealtimeuse_less_75k = svyolr(factor(screen13_y) ~ mealtime_screenuse + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.less.75k)
# outcome = mature video game, exposure = mealtime screenuse, more than $75k
svyolr_vidgame_mealtimeuse_more_75k = svyolr(factor(screen13_y) ~ mealtime_screenuse + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.more.75k)

# outcome = R rated movie, exposure = mealtime screenuse, less than $75k
svyolr_rmovie_mealtimeuse_less_75k = svyolr(factor(screen14_y) ~ mealtime_screenuse + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.less.75k)
# outcome = R rated movie, exposure = mealtime screenuse, more than $75k
svyolr_rmovie_mealtimeuse_more_75k = svyolr(factor(screen14_y) ~ mealtime_screenuse + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.more.75k)

# outcome = mature video game, exposure = bedroom screenuse, less than $75k
svyolr_vidgame_bedroomuse_less_75k = svyolr(factor(screen13_y) ~ bedroom_screenuse + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.less.75k)
# outcome = mature video game, exposure = bedroom screenuse, more than $75k
svyolr_vidgame_bedroomuse_more_75k = svyolr(factor(screen13_y) ~ bedroom_screenuse + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.more.75k)

# outcome = R rated movie, exposure = bedroom screenuse, less than $75k
svyolr_rmovie_bedroomuse_less_75k = svyolr(factor(screen14_y) ~ bedroom_screenuse + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.less.75k)
# outcome = R rated movie, exposure = bedroom screenuse, more than $75k
svyolr_rmovie_bedroomuse_more_75k = svyolr(factor(screen14_y) ~ bedroom_screenuse + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.more.75k)

# outcome = mature video game, exposure = screen control, less than $75k
svyolr_vidgame_screencontrol_less_75k = svyolr(factor(screen13_y) ~ screen_control + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.less.75k)
# outcome = mature video game, exposure = screen control, more than $75k
svyolr_vidgame_screencontrol_more_75k = svyolr(factor(screen13_y) ~ screen_control + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.more.75k)

# outcome = R rated movie, exposure = screen control, less than $75k
svyolr_rmovie_screencontrol_less_75k = svyolr(factor(screen14_y) ~ screen_control + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.less.75k)
# outcome = R rated movie, exposure = screen control, more than $75k
svyolr_rmovie_screencontrol_more_75k = svyolr(factor(screen14_y) ~ screen_control + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.more.75k)

# outcome = mature video game, exposure = monitor screentime, less than $75k
svyolr_vidgame_monitor_less_75k = svyolr(factor(screen13_y) ~ monitor_screentime + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.less.75k)
# outcome = mature video game, exposure = monitor screentime, more than $75k
svyolr_vidgame_monitor_more_75k = svyolr(factor(screen13_y) ~ monitor_screentime + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.more.75k)

# outcome = R rated movie, exposure = monitor screentime, less than $75k
svyolr_rmovie_monitor_less_75k = svyolr(factor(screen14_y) ~ monitor_screentime + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.less.75k)
# outcome = R rated movie, exposure = monitor screentime, more than $75k
svyolr_rmovie_monitor_more_75k = svyolr(factor(screen14_y) ~ monitor_screentime + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.more.75k)

# outcome = mature video game, exposure = limit screentime, less than $75k
svyolr_vidgame_limit_less_75k = svyolr(factor(screen13_y) ~ limit_screentime + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.less.75k)
# outcome = mature video game, exposure = limit screentime, more than $75k
svyolr_vidgame_limit_more_75k = svyolr(factor(screen13_y) ~ limit_screentime + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.more.75k)

# outcome = R rated movie, exposure = limit screentime, less than $75k
svyolr_rmovie_limit_less_75k = svyolr(factor(screen14_y) ~ limit_screentime + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.less.75k)
# outcome = R rated movie, exposure = limit screentime, more than $75k
svyolr_rmovie_limit_more_75k = svyolr(factor(screen14_y) ~ limit_screentime + age_w3 + factor(female) + factor(race) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat.more.75k)
```

### Interaction models
```{r Appendix G: binary household income INTERACTION - models}
# outcome = mature video game, exposure = screen modeling
svyolr_vidgame_screenmodel_inc = svyolr(factor(screen13_y) ~ screen_modeling*factor(HHincomebiv_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = screen modeling
svyolr_rmovie_screenmodel_inc = svyolr(factor(screen14_y) ~ screen_modeling*factor(HHincomebiv_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = mature video game, exposure = mealtime screenuse
svyolr_vidgame_mealtimeuse_inc  = svyolr(factor(screen13_y) ~ mealtime_screenuse*factor(HHincomebiv_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married) , design=svy.dat)

# outcome = R rated movies, exposure = mealtime screenuse
svyolr_rmovie_mealtimeuse_inc  = svyolr(factor(screen14_y) ~ mealtime_screenuse*factor(HHincomebiv_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = mature video game, exposure = bedroom screenuse
svyolr_vidgame_bedroomuse_inc = svyolr(factor(screen13_y) ~ bedroom_screenuse*factor(HHincomebiv_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = bedroom screenuse
svyolr_rmovie_bedroomuse_inc = svyolr(factor(screen14_y) ~ bedroom_screenuse*factor(HHincomebiv_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = mature video game, exposure = screen control
svyolr_vidgame_screencontrol_inc = svyolr(factor(screen13_y) ~ screen_control*factor(HHincomebiv_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = screen control
svyolr_rmovie_screencontrol_inc = svyolr(factor(screen14_y) ~ screen_control*factor(HHincomebiv_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat) 

# outcome = mature video game, exposure = monitor screentime
svyolr_vidgame_monitor_inc = svyolr(factor(screen13_y) ~ monitor_screentime*factor(HHincomebiv_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = monitor screentime
svyolr_rmovie_monitor_inc = svyolr(factor(screen14_y) ~ monitor_screentime*factor(HHincomebiv_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = mature video game, exposure = limit screentime
svyolr_vidgame_limit_inc = svyolr(factor(screen13_y) ~ limit_screentime*factor(HHincomebiv_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)

# outcome = R rated movies, exposure = limit screentime
svyolr_rmovie_limit_inc = svyolr(factor(screen14_y) ~ limit_screentime*factor(HHincomebiv_new) + age_w3 + factor(female) + factor(race) + factor(HHincomebiv_new) + factor(parenteduc_new) + factor(site_id) + factor(COVID_y3) + factor(married), design=svy.dat)
```

### Tables
``` {r Appendix G: tables}
categories <- c(
    "",
    "Parental screen time modeling",
    "Mealtime screen use",
    "Bedroom screen use",
    "Use of screens to control behavior",
    "Parental monitoring of screen time",
    "Limiting screen time"
)
vidgames_less_75k <- c("Odds Ratio (95% CI)",
  or_ci(svyolr_vidgame_screenmodel_less_75k), 
  or_ci(svyolr_vidgame_mealtimeuse_less_75k), 
  or_ci(svyolr_vidgame_bedroomuse_less_75k), 
  or_ci(svyolr_vidgame_screencontrol_less_75k), 
  or_ci(svyolr_vidgame_monitor_less_75k), 
  or_ci(svyolr_vidgame_limit_less_75k)
)
vidgames_less_75k_p <- c("",
  p_value(svyolr_vidgame_screenmodel_less_75k), 
  p_value(svyolr_vidgame_mealtimeuse_less_75k), 
  p_value(svyolr_vidgame_bedroomuse_less_75k), 
  p_value(svyolr_vidgame_screencontrol_less_75k), 
  p_value(svyolr_vidgame_monitor_less_75k), 
  p_value(svyolr_vidgame_limit_less_75k)                     
)
rmovie_less_75k <- c(
  "Odds Ratio (95% CI)", 
  or_ci(svyolr_rmovie_screenmodel_less_75k),
  or_ci(svyolr_rmovie_mealtimeuse_less_75k),
  or_ci(svyolr_rmovie_bedroomuse_less_75k),
  or_ci(svyolr_rmovie_screencontrol_less_75k),
  or_ci(svyolr_rmovie_monitor_less_75k),
  or_ci(svyolr_rmovie_limit_less_75k)
)
rmovie_less_75k_p <- c(
  "",
  p_value(svyolr_rmovie_screenmodel_less_75k),
  p_value(svyolr_rmovie_mealtimeuse_less_75k),
  p_value(svyolr_rmovie_bedroomuse_less_75k),
  p_value(svyolr_rmovie_screencontrol_less_75k),
  p_value(svyolr_rmovie_monitor_less_75k),
  p_value(svyolr_rmovie_limit_less_75k)
)
vidgames_more_75k <- c("Odds Ratio (95% CI)",
  or_ci(svyolr_vidgame_screenmodel_more_75k), 
  or_ci(svyolr_vidgame_mealtimeuse_more_75k), 
  or_ci(svyolr_vidgame_bedroomuse_more_75k), 
  or_ci(svyolr_vidgame_screencontrol_more_75k), 
  or_ci(svyolr_vidgame_monitor_more_75k), 
  or_ci(svyolr_vidgame_limit_more_75k)
)
vidgames_more_75k_p <- c(
  "",
  p_value(svyolr_vidgame_screenmodel_more_75k), 
  p_value(svyolr_vidgame_mealtimeuse_more_75k), 
  p_value(svyolr_vidgame_bedroomuse_more_75k), 
  p_value(svyolr_vidgame_screencontrol_more_75k), 
  p_value(svyolr_vidgame_monitor_more_75k), 
  p_value(svyolr_vidgame_limit_more_75k)
)
rmovie_more_75k <- c(
  "Odds Ratio (95% CI)", 
  or_ci(svyolr_rmovie_screenmodel_more_75k),
  or_ci(svyolr_rmovie_mealtimeuse_more_75k),
  or_ci(svyolr_rmovie_bedroomuse_more_75k),
  or_ci(svyolr_rmovie_screencontrol_more_75k),
  or_ci(svyolr_rmovie_monitor_more_75k),
  or_ci(svyolr_rmovie_limit_more_75k)
)
rmovie_more_75k_p <- c(
  "",
  p_value(svyolr_rmovie_screenmodel_more_75k),
  p_value(svyolr_rmovie_mealtimeuse_more_75k),
  p_value(svyolr_rmovie_bedroomuse_more_75k),
  p_value(svyolr_rmovie_screencontrol_more_75k),
  p_value(svyolr_rmovie_monitor_more_75k),
  p_value(svyolr_rmovie_limit_more_75k)
)
appG_stratbyincome <- tibble(
  "Media parenting practice categories" = categories,
  "Frequency of Mature Video Games (Less than $75k)" = vidgames_less_75k,
  "Mature Video Games (Less than $75k) p-value" = vidgames_less_75k_p,
  "R-rated Movies Consumption (Less than $75k)" = rmovie_less_75k,
  "R-rated Movies (Less than $75k) p-value" = rmovie_less_75k_p,
  "Frequency of Mature Video Games ($75K+)" = vidgames_more_75k,
  "Mature Video Games ($75K+) p-value" = vidgames_more_75k_p,
  "R-rated Movies Consumption ($75K+)" = rmovie_more_75k,
  "R-rated Movies ($75K+)" = rmovie_more_75k_p
)

appG_stratbyincome

# Make interaction term p-value table
vidgames_inc_p <- c(
  "",
  p_value_int(svyolr_vidgame_screenmodel_inc), 
  p_value_int(svyolr_vidgame_mealtimeuse_inc), 
  p_value_int(svyolr_vidgame_bedroomuse_inc), 
  p_value_int(svyolr_vidgame_screencontrol_inc), 
  p_value_int(svyolr_vidgame_monitor_inc), 
  p_value_int(svyolr_vidgame_limit_inc)
)
rmovie_inc_p <- c(
  "",
  p_value_int(svyolr_rmovie_screenmodel_inc), 
  p_value_int(svyolr_rmovie_mealtimeuse_inc), 
  p_value_int(svyolr_rmovie_bedroomuse_inc), 
  p_value_int(svyolr_rmovie_screencontrol_inc), 
  p_value_int(svyolr_rmovie_monitor_inc), 
  p_value_int(svyolr_rmovie_limit_inc)
)
appG_incomeint <- tibble(
  "Media parenting practice categories" = categories,
  "Frequency of Mature Video Games" = vidgames_inc_p,
  "R-rated Movies Consumption" = rmovie_inc_p
)

appG_incomeint
```